version: '3'

services:
  app:
    command: yarn start
    env_file: .env
    image: node:latest
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 36449:36449
    volumes:
      - .:/app
    working_dir: /app
    links:
       - redis

  redis:
    image: redis:latest