services:
  app:
    command: npm start
    env_file:
      - .env
    image: node:22
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 36449:36449
    volumes:
      - .:/app
    working_dir: /app
    links:
      - redis
    restart: always
  redis:
    image: redis:latest
