version: '3'

services:
  app:
    command: yarn start
    env_file: .env
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    links:
       - redis

  redis:
    image: redis:latest